### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [openchange/openchange#234]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/openchange/openchange/blob/a406a05de821e06cf82d6c34dfa792c55549abec/configure.ac#L501 "Configuration checks")?

**Comment by bradh** [comment]
I'm not sure I understand this. I though AX_PTHREAD made pthreads a hard dependency, which isn't what we're looking for.

Perhaps you can propose a patch, which might be easier to understand?

**Comment by elfring** [comment]
How do you think about to look also at build specifications from other free software which is reusing the macro "AX_PTHREAD" already?

**Comment by bradh** [comment]
I think that seems like a lot of work for something that already works for us. configure scripts are inherently brittle because of the lack of test coverage, so I don't think a change is warranted unless you have something that is causing problems for you.
