### ISSUE TITLE
Package openchange-ocsmanager : Depends: python-ocsmanager

### ISSUE THREAD

**Issue by MisterM74** [openchange/openchange#242]
Hello

I have a package cares, is that this version of error is correct?

apt-get install openchange-ocsmanager
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openchange-ocsmanager : Depends: python-ocsmanager (= 1:2.0.r3669-1~inverse1.0) but 1:2.2-5 is to be installed
E: Unable to correct problems, you have held broken packages.

Yours

Mz

**Comment by jkerihuel** [comment]
This package comes from inverse and should therefore be a question for them. I'm afraid there is nothing the openchange team can do for you in this specific context.
