### ISSUE TITLE
samba 4.2 - openchange - build error 

### ISSUE THREAD

**Issue by m-osmani** [openchange/openchange#249]
Hello,

compiling openchange against samba 4.1.11 works fine. BUT we need samba 4.2 because of the new feature "user locking". At the moment i cant build openchange against samba 4.2 

See: http://tracker.openchange.org/boards/2/topics/423?r=428#message-428

Besides my openchange-dc runs at the  moment in full sync with one standalone samba 4.2 ad-dc and repl works fine after joining samba-clean to openchange. 

BUT the real problem comes in my mind that i have two official funktional DC with different samba Version. 4.2 supports locking but 4.1.11 not. And the selection between these DC for logon is round robin based. So it is very important for me to have on both sides 

Openchange-4.2-DC 
Samba-4.2-DC 

Thx for your Support.

Regards 
Masi

**Comment by jelmer** [comment]
Thanks for the patch. However, this needs to be fixed in Samba instead, not in OpenChange. These symbols should not be hidden if external users like OpenChange rely on them.

**Comment by m-osmani** [comment]
I can understand your opinion. Im not a c-code developer but what can i or you do to make it possible to build openchange against samba 4.2?

**Comment by m-osmani** [comment]
Any Suggestion or Solution?

**Comment by jelmer** [comment]
It's not possible to build OpenChange against Samba at the moment. A workaround would be either the patch you suggested or building Samba with commit 25df58a853d8d3ecab2705687453193cb676976c reverted.

**Comment by m-osmani** [comment]
This patch: http://tracker.openchange.org/attachments/258/samba-debug-private-lib.patch
removes only this error:
/usr/bin/ld: utils/openchangeclient.o: undefined reference to symbol 'DEBUGLEVEL_CLASS@SAMBA_4.2.0'

BUT NOT:
######################
Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_connect’:
mapiproxy/dcesrv_mapiproxy.c:135:5: error: dereferencing pointer to incomplete type
b->assoc_group_id = dce_call->pkt.u.bind.assoc_group_id;
^
mapiproxy/dcesrv_mapiproxy.c:138:5: error: dereferencing pointer to incomplete type
b->assoc_group_id = dce_call->pkt.u.alter.assoc_group_id;
^
mapiproxy/dcesrv_mapiproxy.c:155:55: error: ‘struct dcerpc_pipe’ has no member named ‘assoc_group_id’
dce_call->context->assoc_group->id = private->c_pipe->assoc_group_id;
^
mapiproxy/dcesrv_mapiproxy.c:170:55: error: ‘struct dcerpc_pipe’ has no member named ‘assoc_group_id’
dce_call->context->assoc_group->id = private->c_pipe->assoc_group_id;
^
make: *** [mapiproxy/dcesrv_mapiproxy.po] error 1 
########################################################

What do you think, when this problem could be fixed ?

**Comment by blaxter** [comment]
https://github.com/openchange/openchange/commit/73a49af50bf0a496cfe62f49e60a662f1d04d685

**Comment by m-osmani** [comment]
@blaxter: Do you think the solution is to make a revert patch for commit:

73a49af from https://github.com/openchange/openchange/commits/jkerihuel/samba-4.2.0-fix

to fix:

Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
....

error

Thx for your support!

**Comment by blaxter** [comment]
A revert? No the contrary.

I guess that openchange master + that commit + the previous patch for samba should work.
I haven't tested it though

**Comment by m-osmani** [comment]
Thx! I will try it.

**Comment by m-osmani** [comment]
Compile worked. Only one error is:

root@openchange1:/usr/local/src/openchange# make ocsmanager-install
cd mapiproxy/services/ocsmanager && ./setup.py install --root="/" --prefix=/usr/local/samba
Traceback (most recent call last):
  File "./setup.py", line 36, in <module>
    """,
  File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 250, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib/python2.7/distutils/dist.py", line 459, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/usr/lib/python2.7/distutils/fancy_getopt.py", line 258, in getopt
    except getopt.error, msg:
AttributeError: 'module' object has no attribute 'error'
make: *** [ocsmanager-install] Fehler 1

#####################

root@openchange1:/usr/local/src/openchange# env

PYTHONPATH=:/usr/local/samba/lib/python2.7/site-packages:/usr/local/samba/lib/python2.7/site-packages/samba:/usr/local/samba/lib/python2.7/site-packages/openchange:/usr/local/samba/lib/mapistore_backends:/usr/local/samba/lib/python2.7/site-packages/openchange/web:/usr/local/src/openchange/python/openchange/web/auth:/usr/local/samba/lib/python2.7/site-packages/openchange/web/rpcproxy/rpcproxy

PKG_CONFIG_PATH=:/usr/local/samba/lib/pkgconfig

#######################

Any Idea ?

**Comment by m-osmani** [comment]
@blaxter & @jelmer 

Thanks a lot for your support!!! I was successful to build openchange against samba 4.2.0.

Regards
Masi

**Comment by djlucas** [comment]
Okay, so are there any issues with linking to the samba debug libs (short of the samba devs desire not to do so and the possibility of the patch set growing if samba devs change it)? This is exactly what I've been doing for a few months now. I can post a link to the patch for 2.3, but don't want to do so if you are taking OpenChange in a different direction for this. From my reading of the previous thread, it looks to me like Samba devs will ultimately not revert the move of the samba private libs.

**Comment by jelmer** [comment]
Samba is going to revert the use of private libraries for DEBUG. Nobody is actively working on that at the moment though.
