### ISSUE TITLE
Error during the compilation

### ISSUE THREAD

**Issue by TiWim** [openchange/openchange#289]
Hello,
I a, trying to compile the sources but I face a bug during the compilation since this morning because one of you modified the sources.

Here is the bug:

Compiling mapiproxy/libmapiproxy/backends/openchangedb_logger.c with -fPIC
Compiling mapiproxy/libmapiproxy/mapi_handles.c with -fPIC
Compiling mapiproxy/libmapiproxy/entryid.c with -fPIC
Compiling mapiproxy/libmapiproxy/modules.c with -fPIC
Compiling mapiproxy/libmapiproxy/fault_util.c with -fPIC
Compiling mapiproxy/util/schema_migration.c with -fPIC
In file included from /usr/include/python2.7/Python.h:8:0,
                 from mapiproxy/util/schema_migration.c:28:
/usr/include/python2.7/pyconfig.h:1161:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
In file included from /usr/include/stdlib.h:25:0,
                 from /usr/local/samba/include/talloc.h:28,
                 from mapiproxy/util/schema_migration.h:25,
                 from mapiproxy/util/schema_migration.c:22:
/usr/include/features.h:163:0: note: this is the location of the previous definition
In file included from /usr/include/python2.7/Python.h:8:0,
                 from mapiproxy/util/schema_migration.c:28:
/usr/include/python2.7/pyconfig.h:1183:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
In file included from /usr/include/stdlib.h:25:0,
                 from /usr/local/samba/include/talloc.h:28,
                 from mapiproxy/util/schema_migration.h:25,
                 from mapiproxy/util/schema_migration.c:22:
/usr/include/features.h:165:0: note: this is the location of the previous definition
Linking mapiproxy/libmapiproxy.so.2.2
Linking mapiproxy/libmapistore.so.2.2
ln -fs mapiproxy/libmapistore.so.2.2 libmapistore.so.0
mkdir --parent "setup/mapistore"
libmapi/conf/mparse.pl --parser=mapistore_namedprops --outputdir=setup/mapistore/ libmapi/conf/mapi-named-properties
Parsing libmapi/conf/mapi-named-properties
Generating setup/mapistore/mapistore_namedprops.ldif
Compiling mapiproxy/libmapistore/tests/mapistore_test.c
Linking bin/mapistore_test
mapiproxy/libmapistore.so.2.2: undefined reference to `memcached_exist'
collect2: error: ld returned 1 exit status
make: *** [bin/mapistore_test] Error 1

Just before, I had an other problem, it asked me to install nanomsg. For two days I didn't had to.

Thank you for taking care of this,

sincerely

TiWim

**Comment by jkerihuel** [comment]
You need to install memcached libraries more recent than the one on your system.

This is a problem affecting Ubuntu users running trusty distribution.

**Comment by TiWim** [comment]
Thank you for your quick response but I have already installed memcached. I am working on a fresh installed VM.

**Comment by jkerihuel** [comment]
Did you install memcached from sources or using the packages of your distribution?

**Comment by TiWim** [comment]
I used the packages.

**Comment by jkerihuel** [comment]
If your distribution is Ubuntu 14.04, then the package is outdated. We should ask for a backport from Vivid to leverage memcached 1.0.18 instead of the buggy 1.0.8 currently being shipped.

**Comment by TiWim** [comment]
I have a Debian. And yes, the version is out of date. Thank you.

**Comment by TiWim** [comment]
There is an other error. This time it is not my fault.
Some one forget to define DCESRV_CALL_STATE_FLAG_MULTIPLEXED
in mapiproxy/dcesrv_mapiproxy.c:

Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_bind’:
mapiproxy/dcesrv_mapiproxy.c:258:27: error: ‘DCESRV_CALL_STATE_FLAG_MULTIPLEXED’ undeclared (first use in this function)
mapiproxy/dcesrv_mapiproxy.c:258:27: note: each undeclared identifier is reported only once for each function it appears in
mapiproxy/dcesrv_mapiproxy.c: At top level:
mapiproxy/dcesrv_mapiproxy.c:735:13: warning: ‘dcesrv_mapiproxy_lp_defaults’ defined but not used [-Wunused-function]
make: *** [mapiproxy/dcesrv_mapiproxy.po] Error 1

**Comment by jkerihuel** [comment]
You hit this problem because you need a Samba version 4.1.17 with 2 patches. These patches have entered master and are scheduled for 4.1.18 release to be shipped in a few days.

In the meanwhile, you have 2 approaches: 

* build Samba 4.1.17 with the following patches
  * https://attachments.samba.org/attachment.cgi?id=10972
  * https://attachments.samba.org/attachment.cgi?id=10971

* install the pre-packaged version we are using at the moment from openchange travis-deps ppa:
 * https://launchpad.net/~openchange/+archive/ubuntu/travis-deps/

**Comment by TiWim** [comment]
Hello, it's me again. I compiled the sources with your hints but during the configuration of the server there is still a problem. When I test the server connectivity, it prints me following lines: 

...
DCERPC endpoint server 'exchange_ds_rfr' registered
DCERPC endpoint server 'mapiproxy' registered
MAPIPROXY server mode enabled
mapiproxy/libmapiproxy/dcesrv_mapiproxy_server.c:187(mapiproxy_server_load): MAPIPROXY proxy mode disabled
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c:1559(dcesrv_exchange_nsp_init): dcesrv_exchange_nsp_init
Using MySQL backend for openchangedb: mysql://openchangeuser:openchange*123@localhost/openchange
dreplsrv_partition[CN=Configuration,DC=openbar,DC=local] loaded
...

There is missing some lines here and then, I have problems to connect with an outlook client.

Thanks,

TiWim

**Comment by jkerihuel** [comment]
The log you've pasted does highlight any anomaly. More information would be required to help you and the openchange devel mailing-list would be a more suitable media for this.

Cheers,
Julien.

**Comment by bkoffler** [comment]
I know this is an old thread but i am running into the same problem. Here is the error i am seeing when i try to 'make':

Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_bind’:
mapiproxy/dcesrv_mapiproxy.c:258:27: error: ‘DCESRV_CALL_STATE_FLAG_MULTIPLEXED’ undeclared (first use in this function)
  dce_call->state_flags |= DCESRV_CALL_STATE_FLAG_MULTIPLEXED;
                           ^
mapiproxy/dcesrv_mapiproxy.c:258:27: note: each undeclared identifier is reported only once for each function it appears in
mapiproxy/dcesrv_mapiproxy.c: At top level:
mapiproxy/dcesrv_mapiproxy.c:735:13: warning: ‘dcesrv_mapiproxy_lp_defaults’ defined but not used [-Wunused-function]
 static bool dcesrv_mapiproxy_lp_defaults(struct loadparm_context *lp_ctx)
             ^
make: *** [mapiproxy/dcesrv_mapiproxy.po] Error 1

I'm still trying to compile to software so i am new to this software.. looking forward to getting it to work though..

Please let me know what you think when you have a chance.

Thanks,

Brian
