### ISSUE TITLE
Implementation of Exchange Web Services (EWS)

### ISSUE THREAD

**Issue by m-osmani** [openchange/openchange#290]
Hello,

According to this source
http://www.openchange.org/cookbook/ocsmanager.html

the implementation of Exchange Web Services is at the moment partial. 

There a lot of Enterprise Software which use the EWS API. Is there hope for full implementation or maybe for calendar management over EWS (ocsmanager).  

Regards

**Comment by jkerihuel** [comment]
At the moment, we do not have any specific plan on Implementing the calendar API over EWS in OpenChange in the short term.
