### ISSUE TITLE
setup: finding domain, realm and address

### ISSUE THREAD

**Issue by fommil** [openchange/openchange#357]
The docs here describe how to set up a profile
http://www.openchange.org/documentation/howto/openchangeclient_setup.html
but do not show how the user can find his/her domain/realm/address. It would be useful if there was a short description or a link to microsoft documentation on the matter (although I have been unable to find any of the latter). Is there any way to autodiscover this stuff?

**Comment by bradh** [comment]
There is no autodiscovery support in openchange (at least, not on the client side) yet. There is autodiscovery support in the protocol docs, but it makes assumptions about domain connectivity that may not exist. 

Ask your sysadmin for the entries - which ones you need depends on how the server was set up, and how you are authenticating.

**Comment by fommil** [comment]
I asked and they don't know what you mean.... Realm and Domain mean the same thing to them.

**Comment by fommil** [comment]
But I did work out where the server lives and I think it uses kerberos.

**Comment by bradh** [comment]
Domain = NTLM domain, Realm is the DNS-type name (from Kerberos). 

There is an example in the man page of setting up a kerberos account, but you can probably just use NTLM style, depending on what your admins did, and the version of exchange you are connecting too.
