### ISSUE TITLE
openchangeclient with linux console: no subject is taken for the e-mail

### ISSUE THREAD

**Issue by knieselpriem** [openchange/openchange#365]
When I'm trying to send an e-mail with openchangeclient, no subject is overtaken for the e-mail. The received e-mail has no subject!

Command line:
- openchangeclient --to="test@network.lan" -s "test subject'" -B "This is a simple test..." --sendmail

Console output:
params.c:pm_process() - Processing configuration file "/etc/samba/openchange.conf"
params.c:pm_process() - Processing configuration file "/etc/samba/shares.conf"
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'schannel' registered
GENSEC backend 'spnego' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'krb5' registered
GENSEC backend 'fake_gssapi_krb5' registered
Using binding ncacn_ip_tcp:mail.network.lan
Server exchangeRFR/MAIL.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeRFR/MAIL.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
Using binding ncacn_ip_tcp:s03.network.lan
Server exchangeAB/S03.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeAB/S03.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
Using binding ncacn_ip_tcp:mail.network.lan
Server exchangeMDB/MAIL.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeMDB/MAIL.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
    sendmail                 : MAPI_E_SUCCESS (0x0)

OS:
- Linux hf-s03 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 GNU/Linux
- no X-Server / GUI
- Zentyal Development Edition 4.1

**Comment by knieselpriem** [comment]
openchangeclient -V
Version 2.3 (Vulcan)

**Comment by sixstone-qq** [comment]
Are you using OpenChange server, right?

**Comment by knieselpriem** [comment]
Yes, with Zentyal 4.1 (See www.Zentyal.com)

**Comment by sixstone-qq** [comment]
Hello @knieselpriem,

Thanks very much for reporting. The fix here is in server code using the following Pull Request:

https://github.com/Zentyal/sogo/pull/163/files

Please, checkout that branch and install following these instructions:
```
./configure --with-ssl=gnutls --enable-saml2 --enable-debug --prefix=/usr/System
make
cd OpenChange
make
sudo make install
sudo restart samba-ad-dc
```
