### ISSUE TITLE
openchangeclient with linux console: file name of attachments always named like "untitled-2"

### ISSUE THREAD

**Issue by knieselpriem** [openchange/openchange#366]
When I'm trying to send an e-mail with openchangeclient, attachments always named like "untitled-2". The original file name is not overtaken!

Command line:
- openchangeclient --to="test@network.lan" -s "test subject'" -B "This is a simple test..." -A "test.txt" --sendmail

or
- openchangeclient --to="test@network.lan" -s "test subject'" -B "This is a simple test..." -A "/tmp/test.txt" --sendmail

Console output:
filename = test.txt (size = 360 / 360)
params.c:pm_process() - Processing configuration file "/etc/samba/openchange.conf"
params.c:pm_process() - Processing configuration file "/etc/samba/shares.conf"
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'schannel' registered
GENSEC backend 'spnego' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'krb5' registered
GENSEC backend 'fake_gssapi_krb5' registered
Using binding ncacn_ip_tcp:mail.network.lan
Server exchangeRFR/MAIL.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeRFR/MAIL.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
Using binding ncacn_ip_tcp:s03.network.lan
Server exchangeAB/S03.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeAB/S03.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
Using binding ncacn_ip_tcp:mail.network.lan
Server exchangeMDB/MAIL.NETWORK.LAN@NETWORK.LAN is not registered with our KDC:  Miscellaneous failure (see text): Matching credential (exchangeMDB/MAIL.NETWORK.LAN@NETWORK.LAN) not found
SPNEGO(gssapi_krb5) creating NEG_TOKEN_INIT failed: NT_STATUS_INVALID_PARAMETER
Got challenge flags:
Got NTLMSSP neg_flags=0x60898205
NTLMSSP: Set final flags:
Got NTLMSSP neg_flags=0x60088205
Sending test.txt:
openstream: retval = MAPI_E_SUCCESS (0x00000000)
We are about to write 360 bytes in the stream
.    sendmail                 : MAPI_E_SUCCESS (0x0)

OS:
- Linux hf-s03 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 GNU/Linux
- no X-Server / GUI
- Zentyal Development Edition 4.1

**Comment by knieselpriem** [comment]
openchangeclient -V
Version 2.3 (Vulcan)

**Comment by sixstone-qq** [comment]
Hello @knieselpriem,

Thanks very much for reporting it.

It should be fixed with the following Pull Request:

https://github.com/openchange/openchange/pull/369

To compile and install this version, checkout this branch and do what the following link says:
http://openchange.org/documentation/howto/zentyal_developer.html#compile-and-install-openchange
