### ISSUE TITLE
Document IMAP requirements for SOGo+OpenChange

### ISSUE THREAD

**Issue by qantourisc** [openchange/openchange#372]
The documentation at
http://www.openchange.org/cookbook/backends/sogo/index.html and
http://www.openchange.org/cookbook/backends/sogo/dovecot.html
does not mention that your IMAP backend-end cannot use password authentication. (Or at-least not all possible password back-ends) 
Example for dovecot.
passdb {
    driver = static
    args = nopassword=y allow_nets=127.0.0.1/32
}

If I do not add this I get: [auth] pam_krb5(dovecot:auth): authentication failure; (from dovecot)

**Comment by jkerihuel** [comment]
@qantourisc Thanks for reporting, but can you please use the appropriate repository. The documentation you are referring to is actually available within the http://github.com/openchange/website repository and you can directly issue a pull request from there.

Thanks!
Julien.

**Comment by qantourisc** [comment]
Ow my bad, didn't knew there was one. But this was based on sogo.nu documentation, witch at second sight isn't required after all. I'll do more digging before posting it again.

**Comment by jkerihuel** [comment]
:+1:
