### ISSUE TITLE
set_mapistoreURI returning MAPI_E_NOT_FOUND if mapping is alreay in database.

### ISSUE THREAD

**Issue by qantourisc** [openchange/openchange#373]
In  the file:
mapiproxy/libmapiproxy/backends/openchangedb_mysql.c:323 MAPISTATUS set_mapistoreURI
The query can return `Query OK, 0 rows affected; Rows matched: 1  Changed: 0`
Meaning the row is already on the requested value.
I had to change the check `if (mysql_affected_rows(conn) == 0) {` to `if (mysql_num_rows(conn) == 0){`

Please confirm this bug and I can make a pull request.

**Comment by qantourisc** [comment]
And another possible victim: set_system_idx(

**Comment by sixstone-qq** [comment]
You're right @qantourisc . I've just added a unit test for this case with the following result:

```
testsuite/libmapiproxy/openchangedb.c:177:F:Openchangedb MySQL backend:test_set_mapistoreURI:0: Assertion 'retval==MAPI_E_SUCCESS' failed: retval==-2147221233, MAPI_E_SUCCESS==0
```

**Comment by qantourisc** [comment]
Pull request: https://github.com/openchange/openchange/pull/378

**Comment by qantourisc** [comment]
Yes and Hell No: See my patch: https://github.com/openchange/openchange/pull/378

Why yes: It looks like it will work.

Why no:
Why on earth would you do twice the work ? You read the wrong docs on mysql_***_rows if I'm not mistaking. And you do not need to change the DB connection settings to use mysql_num_rows.

You have to look @ https://dev.mysql.com/doc/refman/5.5/en/mysql-num-rows.html not @ https://dev.mysql.com/doc/refman/5.5/en/mysql-affected-rows.html.
"mysql_num_rows() is intended for use with statements that return a result set, such as SELECT. For statements such as INSERT, UPDATE, or DELETE, the number of affected rows can be obtained with mysql_affected_rows(). " Translation (or atleast how I read it): num_rows() will select the number of rows matches by the WHERE. If you want  to know howmany rows you updated: use affected_rows()

Side thought: We also ought to check for >1 cause that is also wrong, if one wishes to protect against DB-schema bugs, and code bugs. But not really required.

**Comment by sixstone-qq** [comment]
I obtained the value for mysql_num_rows after executing the UPDATE query and here you are the results:
```C
   printf("Count %d affected %d\n", mysql_num_rows(conn), mysql_affected_rows(conn));
```
The results after running testsuite.
```
Count 39703056 affected 1
Count 39703056 affected 0
```
So for me the mysql_num_rows is not set on UPDATE statements.

**Comment by qantourisc** [comment]
Ok this is where mysql and mariadb differ it seems.So your solution is correct.
