### ISSUE TITLE
Error During Compilation 

### ISSUE THREAD

**Issue by bkoffler** [openchange/openchange#403]
I put this same comment down under 289 as it was the same issue, but since that issue is closed i wasn't sure if anyone would see my comments.

Here is the error i am seeing when i try to compile:

Compiling mapiproxy/dcesrv_mapiproxy.c with -fPIC
mapiproxy/dcesrv_mapiproxy.c: In function ‘mapiproxy_op_bind’:
mapiproxy/dcesrv_mapiproxy.c:258:27: error: ‘DCESRV_CALL_STATE_FLAG_MULTIPLEXED’ undeclared (first use in this function)
dce_call->state_flags |= DCESRV_CALL_STATE_FLAG_MULTIPLEXED;
^
mapiproxy/dcesrv_mapiproxy.c:258:27: note: each undeclared identifier is reported only once for each function it appears in
mapiproxy/dcesrv_mapiproxy.c: At top level:
mapiproxy/dcesrv_mapiproxy.c:735:13: warning: ‘dcesrv_mapiproxy_lp_defaults’ defined but not used [-Wunused-function]
static bool dcesrv_mapiproxy_lp_defaults(struct loadparm_context lp_ctx)
^
make: ** [mapiproxy/dcesrv_mapiproxy.po] Error 1

I am new to this software and trying to move past this point.. looking forward to getting it to work though..

Please let me know what you think when you have a chance.

Thanks,

Brian

**Comment by alecpl** [comment]
Searching for DCESRV_CALL_STATE_FLAG_MULTIPLEXED in the Internet gives an answer that it was added to Samba on May 2015 in both 4.1 and 4.2 branches. Finding which Samba versions have it is an exercise for you.

**Comment by blaxter** [comment]
yep, @alecpl is right, basically you are using an old version of samba, you need at least 4.1.18

**Comment by bkoffler** [comment]
Thanks guys - i think i was looking too broadly.. I'm still not sure why the repo i pulled from gave me an outdated version but that's an issue i can deal with later..
