### ISSUE TITLE
Problem compiling [SOLVED]

### ISSUE THREAD

**Issue by alejandro-anv** [openchange/openchange#408]
I am compiling openchange following the instructions of the "cookbook" (http://www.openchange.org/cookbook/index.htmll)

All ok, compiled samba (make samba) but when configuring openchange (./configure --prefix=/usr/local/samba) it reports the error, "checking for samba 4... configure: error: Samba 4 not found". 

I checked /usr/local/samba and the files are there:

total 20
drwxr-xr-x 2 root root 4096 Dec  1 16:12 bin
drwxr-xr-x 2 root root 4096 Dec  1 16:13 include
drwxr-xr-x 3 root root 4096 Dec  1 16:13 lib
drwxr-xr-x 3 root root 4096 Dec  1 16:10 lib64
drwxr-xr-x 3 root root 4096 Dec  1 16:10 share

Any help please?

**Comment by bradh** [comment]
Please show the values of these environment variables:
PKG_CONFIG_PATH
PYTHONPATH

**Comment by alejandro-anv** [comment]
# echo $PKG_CONFIG_PATH
:/usr/local/samba/lib/pkgconfig:/usr/local/samba/lib/pkgconfig
# echo $PYTHONPATH
:/usr/local/samba/lib/python2.7/site-packages:/usr/local/samba/lib/python2.7/site-packages

**Comment by alejandro-anv** [comment]
The error reported is this:

configure:4517: $PKG_CONFIG --exists --print-errors "samba-hostconfig"
Package samba-hostconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `samba-hostconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'samba-hostconfig' found

And this is true. There is _not_ samba-hostconfig.pc in /usr/local/samba. When should it be generated?

**Comment by alejandro-anv** [comment]
Never mind. Just recompiled samba with this lib64 changes and it created the files. 

Now I need to build nanomsg.
