### ISSUE TITLE
Outlook 2016 support

### ISSUE THREAD

**Issue by rnenjoy** [openchange/openchange#412]
When connecting a Microsoft Outlook 2016 to a OpenChange server it says that it is no longer supported. Apparently Outlook 2016 has dropped support for Exchange 2007 which i think OpenChange pretends to be?

It also seems that Outlook 2016 has dropped support for Outlook Anywhere.

**Comment by jkerihuel** [comment]
Indeed, OpenChange does not provide support for Microsoft Outlook 2016 yet. This new version of Outlook makes use of MAPI/HTTP - plain MAPI (what OpenChange implements) on top of HTTP transport layer which is different from Outlook anywhere (ncacn_http). While OpenChange implements the most complex piece, we still have to put things together and link it back to OpenChange server.
